In [1]:
##########################
## Import Libraries and Dependencies
##########################
import sqlite3
import csv
import pandas as pd
from numpy import genfromtxt
from time import time
from datetime import datetime, timedelta
from sqlalchemy import Column, String, Integer, Float, Date, VARCHAR, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy import *
from random import randint
import os
import sys

In [2]:
###################################
## How to use this file
###################################
## Run this file once to create the database from 
## the CSVs in the data file
## Open this file in the terminal and run: python createDB.py

In [3]:
##################################
## SQLAlchemy Declarative base
# ################################
# The declarative base is a function that returns 
# a new base class from which all mapped classes 
# should inherit.
# Refer to these sqlalchemy tutorials:
# https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/basic_use.html
#https://docs.sqlalchemy.org/en/13/core/tutorial.html


#Create the database
engine = create_engine('sqlite:///researchimpactreview.sqlite')

#Map which table in database will be related to each class
Base = declarative_base()

#Create a metadata instance
metadata = MetaData(engine)
#A metadata is an object container that will store attributes and name of table 

#Base.metadata.drop_all(engine)

In [4]:
##################################
## Define Schema (i.e. Create Classes)
##################################
#Create a class that describes each table in the database
#https://images.webofknowledge.com/images/help/WOS/hs_wos_fieldtags.html
# ID column in Wos Documents becomes KP
# extend_existing=True, autoload=True, autoload_with=engine

class WoS_Documents(Base):
    __tablename__ = 'wos_documents'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    PT = Column(VARCHAR(40))
    AU = Column(Text)
    BA = Column(Text)
    BE = Column(Text)
    GP = Column(Text)
    AF = Column(Text)
    BF = Column(Text)
    CA = Column(Text)
    TI = Column(Text)
    SO = Column(Text)
    SE = Column(Text)
    BS = Column(Text)
    LA = Column(Text)
    DT = Column(Text)
    CT = Column(Text)
    CY = Column(Text)
    CL = Column(Text)
    SP = Column(Text)
    HO = Column(Text)
    DE = Column(Text)
    KP = Column(Text)
    AB = Column(Text)
    C1 = Column(Text)
    RP = Column(Text)
    EM = Column(Text)
    RI = Column(Text)
    OI = Column(Text)
    FU = Column(Text)
    FX = Column(Text)
    CR = Column(Text)
    NR = Column(Integer)
    TC = Column(Integer)
    Z9 = Column(Text)
    U1 = Column(Integer)
    U2 = Column(Integer)
    PU = Column(Text)
    PI = Column(Text)
    PA = Column(Text)
    SN = Column(Text)
    EI = Column(Text)
    BN = Column(Text)
    J9 = Column(Text)
    JI = Column(Text)
    PD = Column(Text)
    PY = Column(Text)
    VL = Column(Text)
    IS = Column(Text)
    PN = Column(Text)
    SU = Column(Text)
    SI = Column(Text)
    MA = Column(Text)
    BP = Column(Integer)
    EP = Column(Integer)
    AR = Column(Text)
    DI = Column(Text)
    D2 = Column(Text)
    EA = Column(Text)
    PG = Column(Text)
    WC = Column(Text)
    SC = Column(Text)
    GA = Column(Text)
    UT = Column(Text)
    PM = Column(Text)
    OA = Column(Text)
    HC = Column(Text)
    HP = Column(Text)
    DA = Column(Text)

   
 

class WoS_Documents_Org_Enhanced(Base):
    __tablename__ = 'wos_documents_org_enhanced'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    Organizations_Enhanced = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)
    
    
class WoS_Documents_Funding_Agencies(Base):
    __tablename__ = 'wos_documents_funding_agencies'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    Funding_Agencies = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)

class WoS_Documents_Countries(Base):
    __tablename__ = 'wos_documents_countries'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    Countries_Regions = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)
    
class WoS_Documents_Grant_Numbers(Base):
    __tablename__ = 'wos_documents_grant_numbers'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    Grant_Numbers = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)
    
class WoS_Documents_Citation_Review(Base):
    __tablename__ = 'wos_documents_citation_review'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)  
    Title = Column(Text)
    Authors = Column(Text)
    Corporate_Authors = Column(Text)
    Editors = Column(Text)
    Book_Editors = Column(Text)
    Source_Title = Column(Text)
    Publication_Date = Column(Text)
    Publication_Year = Column(Text)
    Volume = Column(Text)
    Issue = Column(Text)
    Part_Number = Column(Text)
    Supplement = Column(Text)
    Special_Issue = Column(Text)
    Beginning_Page = Column(Integer)
    Ending_page = Column(Integer)
    Article_Number = Column(Text)
    DOI = Column(Text)
    Conference_Title = Column(Text)
    Conference_Date = Column(Text)
    Total_Citations = Column(Integer)
    Average_per_Year = Column(Float)
    y1900 = Column(Integer)
    y1901 = Column(Integer)
    y1902 = Column(Integer)
    y1903 = Column(Integer)
    y1904 = Column(Integer)
    y1905 = Column(Integer)
    y1906 = Column(Integer)
    y1907 = Column(Integer)
    y1908 = Column(Integer)
    y1909 = Column(Integer)
    y1910 = Column(Integer)
    y1911 = Column(Integer)
    y1912 = Column(Integer)
    y1913 = Column(Integer)
    y1914 = Column(Integer)
    y1915 = Column(Integer)
    y1916 = Column(Integer)
    y1917 = Column(Integer)
    y1918 = Column(Integer)
    y1919 = Column(Integer)
    y1920 = Column(Integer)
    y1921 = Column(Integer)
    y1922 = Column(Integer)
    y1923 = Column(Integer)
    y1924 = Column(Integer)
    y1925 = Column(Integer)
    y1926 = Column(Integer)
    y1927 = Column(Integer)
    y1928 = Column(Integer)
    y1929 = Column(Integer)
    y1930 = Column(Integer)
    y1931 = Column(Integer)
    y1932 = Column(Integer)
    y1933 = Column(Integer)
    y1934 = Column(Integer)
    y1935 = Column(Integer)
    y1936 = Column(Integer)
    y1937 = Column(Integer)
    y1938 = Column(Integer)
    y1939 = Column(Integer)
    y1940 = Column(Integer)
    y1941 = Column(Integer)
    y1942 = Column(Integer)
    y1943 = Column(Integer)
    y1944 = Column(Integer)
    y1945 = Column(Integer)
    y1946 = Column(Integer)
    y1947 = Column(Integer)
    y1948 = Column(Integer)
    y1949 = Column(Integer)
    y1950 = Column(Integer)
    y1951 = Column(Integer)
    y1952 = Column(Integer)
    y1953 = Column(Integer)
    y1954 = Column(Integer)
    y1955 = Column(Integer)
    y1956 = Column(Integer)
    y1957 = Column(Integer)
    y1958 = Column(Integer)
    y1959 = Column(Integer)
    y1960 = Column(Integer)
    y1961 = Column(Integer)
    y1962 = Column(Integer)
    y1963 = Column(Integer)
    y1964 = Column(Integer)
    y1965 = Column(Integer)
    y1966 = Column(Integer)
    y1967 = Column(Integer)
    y1968 = Column(Integer)
    y1969 = Column(Integer)
    y1970 = Column(Integer)
    y1971 = Column(Integer)
    y1972 = Column(Integer)
    y1973 = Column(Integer)
    y1974 = Column(Integer)
    y1975 = Column(Integer)
    y1976 = Column(Integer)
    y1977 = Column(Integer)
    y1978 = Column(Integer)
    y1979 = Column(Integer)
    y1980 = Column(Integer)
    y1981 = Column(Integer)
    y1982 = Column(Integer)
    y1983 = Column(Integer)
    y1984 = Column(Integer)
    y1985 = Column(Integer)
    y1986 = Column(Integer)
    y1987 = Column(Integer)
    y1988 = Column(Integer)
    y1989 = Column(Integer)
    y1990 = Column(Integer)
    y1991 = Column(Integer)
    y1992 = Column(Integer)
    y1993 = Column(Integer)
    y1994 = Column(Integer)
    y1995 = Column(Integer)
    y1996 = Column(Integer)
    y1997 = Column(Integer)
    y1998 = Column(Integer)
    y1999 = Column(Integer)
    y2000 = Column(Integer)
    y2001 = Column(Integer)
    y2002 = Column(Integer)
    y2003 = Column(Integer)
    y2004 = Column(Integer)
    y2005 = Column(Integer)
    y2006 = Column(Integer)
    y2007 = Column(Integer)
    y2008 = Column(Integer)
    y2009 = Column(Integer)
    y2010 = Column(Integer)
    y2011 = Column(Integer)
    y2012 = Column(Integer)
    y2013 = Column(Integer)
    y2014 = Column(Integer)
    y2015 = Column(Integer)
    y2016 = Column(Integer)
    y2017 = Column(Integer)
    y2018 = Column(Integer)
    y2019 = Column(Integer)
    y2020 = Column(Integer)
    y2021 = Column(Integer)
    


    
    
class WoS_Citations_WOS_Category (Base):
    __tablename__ = 'wos_citations_WOS_category'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    WOS_Category = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)
    
class WoS_Citations_Years(Base):
    __tablename__ = 'wos_citations_years'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False) 
    Publication_Year = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)
    

class WoS_Citations_Org_Enhanced(Base):
    __tablename__ = 'wos_citations_org_enhanced'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    Organization_Enhanced = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)
    

class WoS_Citations_Funding_Agencies(Base):
    __tablename__ = 'wos_citations_funding_agencies'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    Funding_Agencies = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)
    
class WoS_Citations_Source_Title(Base):
    __tablename__ = 'wos_citations_source_title'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    Source_Title = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)

class WoS_Citations_Book_Series_Title(Base):
    __tablename__ = 'wos_citations_book_series_title'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    Book_Series_Title = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)

class WoS_Citations_Meeting_Title(Base):
    __tablename__ = 'wos_citations_meeting_title'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    Meeting_Title = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)
    
class WoS_Citations_Countries(Base):
    __tablename__ = 'wos_citations_countries'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False) 
    Countries_Regions = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)

class WoS_Citations_Group_Authors(Base):
    __tablename__ = 'wos_citations_group_authors'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False) 
    Group_Authors = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)
    
class WoS_Citations_Language(Base):
    __tablename__ = 'wos_citations_language'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False) 
    Language = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)
    
class WoS_Citations_Research_Areas(Base):
    __tablename__ = 'wos_citations_research_areas'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False) 
    Research_Areas = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)
    
class WoS_Citations_Grant_Numbers(Base):
    __tablename__ = 'wos_citations_grant_numbers'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    Grant_Numbers = Column(Text)
    records = Column(Integer)
    percent = Column(Integer)

class InCites_Documents (Base):
    __tablename__ = 'incites_documents'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    Accession_Number = Column(Text)
    DOI = Column(Text)
    Pubmed_ID = Column(Text)
    Article_Title = Column(Text)
    Link = Column(Text)
    Authors = Column(Text)
    Source = Column(Text)
    Research_Area = Column(Text)
    Document_Type = Column(Text)
    Volume = Column(Text)
    Issue = Column(Text)
    Pages = Column(Text)
    Publication_Date = Column(Text)
    Times_Cited = Column(Integer)
    Journal_Expected_Citations = Column(Float)
    Category_Expected_Citations = Column(Float)
    Journal_Normalized_Citation_Impact = Column(Float)
    Category_Normalized_Citation_Impact = Column(Float)
    Percentile_in_Subject_Area = Column(Float)
    Journal_Impact_Factor = Column(Float)

class InCites_Documents_Journals (Base):
    __tablename__ = 'incites_documents_journals'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    Name = Column(Text)
    Rank = Column(Text)
    Web_of_Science_Documents = Column(Integer)
    Times_Cited = Column(Integer)
    Percent_Docs_Cited = Column(Float)
    Quartile = Column(Text)
    Five_Year_Impact_Factor = Column(Float)
    Article_Influence = Column(Float)
    Category_Normalized_Citation_Impact = Column(Float)
    Cited_Half_Life = Column(Float)
    Eigenfactor = Column(Float)
    Immediacy_Index = Column(Float)
    Impact_Factor_wo_Self_Cites = Column(Float)
    Journal_Impact_Factor = Column(Float)
    Journal_Normalized_Citation_Impact = Column(Float)
    Percent_All_Open_Access_Documents = Column(Float)
    Percent_Bronze_Documents = Column(Float)
    Percent_DOAJ_Gold_Documents = Column(Float)
    Percent_Green_Accepted_Documents = Column(Float)
    Percent_Green_Published_Documents = Column(Float)
    Percent_Other_Gold_Documents = Column(Float)
    All_Open_Access_Documents = Column(Float)
    Bronze_Documents = Column(Integer)
    DOAJ_Gold_Documents = Column(Integer)
    Green_Accepted_Documents = Column(Integer)
    Green_Published_Documents = Column(Integer)
    Other_Gold_Documents = Column(Integer)

class InCites_Citations (Base):
    __tablename__ = 'incites_citations'
    __table_args__ = {'sqlite_autoincrement': True}
    id = Column(Integer, primary_key=True, nullable=False)
    Accession_Number = Column(Text)
    DOI = Column(Text)
    Pubmed_ID = Column(Text)
    Article_Title = Column(Text)
    Link = Column(Text)
    Authors = Column(Text)
    Source = Column(Text)
    Research_Area = Column(Text)
    Document_Type = Column(Text)
    Volume = Column(Text)
    Issue = Column(Text)
    Pages = Column(Text)
    Publication_Date = Column(Text)
    Times_Cited = Column(Integer)
    Journal_Expected_Citations = Column(Float)
    Category_Expected_Citations = Column(Float)
    Journal_Normalized_Citation_Impact = Column(Float)
    Category_Normalized_Citation_Impact = Column(Float)
    Percentile_in_Subject_Area = Column(Float)
    Journal_Impact_Factor = Column(Float)
    

WoS_Documents.__table__.create(bind=engine, checkfirst=True)
WoS_Documents_Org_Enhanced.__table__.create(bind=engine, checkfirst=True)
WoS_Documents_Funding_Agencies.__table__.create(bind=engine, checkfirst=True)
WoS_Documents_Countries.__table__.create(bind=engine, checkfirst=True)
WoS_Documents_Grant_Numbers.__table__.create(bind=engine, checkfirst=True)
WoS_Documents_Citation_Review.__table__.create(bind=engine, checkfirst=True)
WoS_Citations_WOS_Category.__table__.create(bind=engine, checkfirst=True)
WoS_Citations_Years.__table__.create(bind=engine, checkfirst=True)
WoS_Citations_Org_Enhanced.__table__.create(bind=engine, checkfirst=True)
WoS_Citations_Funding_Agencies.__table__.create(bind=engine, checkfirst=True)
WoS_Citations_Source_Title.__table__.create(bind=engine, checkfirst=True)
WoS_Citations_Book_Series_Title.__table__.create(bind=engine, checkfirst=True)
WoS_Citations_Meeting_Title.__table__.create(bind=engine, checkfirst=True)
WoS_Citations_Countries.__table__.create(bind=engine, checkfirst=True)
WoS_Citations_Group_Authors.__table__.create(bind=engine, checkfirst=True)
WoS_Citations_Language.__table__.create(bind=engine, checkfirst=True)
WoS_Citations_Grant_Numbers.__table__.create(bind=engine, checkfirst=True)
InCites_Documents.__table__.create(bind=engine, checkfirst=True)
InCites_Documents_Journals.__table__.create(bind=engine, checkfirst=True)
InCites_Citations.__table__.create(bind=engine, checkfirst=True)

In [5]:
###############################
## Interact with a SQLite database in terminal
###############################
## Open the energydata.db in the terminal 
## Use these commands: 
## sqlite3 energyData.sqlite
## .tables   ## prints a list of the tables in the db
## .schema <table name> ## prints a list of columns and data types in the table
## .dump     ## prints the data in the database
## .exit     ## to exit the db file

##############################
## Interact with a SQLite database via SQLAlchemy in Jupyter Notebooks
##############################
# df = pd.read_sql_query("SELECT * FROM table_name", engine)
# print(df)

In [6]:
####################################
## Extract: Use SQLAlchemy to Load CSV data into Tables
####################################
#Within the if statement that will create the database using 
# the classes that have already been described (see above)

 
def load_1():
    #energy_consumption_sector_data = genfromtxt("../data/Energy_Consumption_by_Sector_2017.csv", delimiter=',', skip_header=1, converters={0: lambda s: str(s)})
    #print(energy_consumption_sector_data)
    #return energy_consumption_sector_data.tolist()
    wos_documents_data = pd.read_csv("../static/data/wos_documents.csv")
    wos_documents_data_list = wos_documents_data.values.tolist()
    #print(wos_documents_data_list)
    return wos_documents_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_1 = load_1()
    #print(data_1)
    for i in data_1:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Documents(**{
                    'PT' : i[0], 
                    'AU' : i[1], 
                    'BA' : i[2], 
                    'BE' : i[3], 
                    'GP' : i[4], 
                    'AF' : i[5], 
                    'BF' : i[6], 
                    'CA' : i[7], 
                    'TI' : i[8], 
                    'SO' : i[9], 
                    'SE' : i[10], 
                    'BS' : i[11], 
                    'LA' : i[12], 
                    'DT' : i[13], 
                    'CT' : i[14], 
                    'CY' : i[15], 
                    'CL' : i[16], 
                    'SP' : i[17], 
                    'HO' : i[18], 
                    'DE' : i[19], 
                    'KP' : i[20], 
                    'AB' : i[21], 
                    'C1' : i[22], 
                    'RP' : i[23], 
                    'EM' : i[24], 
                    'RI' : i[25], 
                    'OI' : i[26], 
                    'FU' : i[27], 
                    'FX' : i[28], 
                    'CR' : i[29], 
                    'NR' : i[30], 
                    'TC' : i[31], 
                    'Z9' : i[32], 
                    'U1' : i[33], 
                    'U2' : i[34], 
                    'PU' : i[35], 
                    'PI' : i[36], 
                    'PA' : i[37], 
                    'SN' : i[38], 
                    'EI' : i[39], 
                    'BN' : i[40], 
                    'J9' : i[41], 
                    'JI' : i[42], 
                    'PD' : i[43], 
                    'PY' : i[44], 
                    'VL' : i[45], 
                    'IS' : i[46], 
                    'PN' : i[47], 
                    'SU' : i[48], 
                    'SI' : i[49], 
                    'MA' : i[50], 
                    'BP' : i[51], 
                    'EP' : i[52], 
                    'AR' : i[53], 
                    'DI' : i[54], 
                    'D2' : i[55], 
                    'EA' : i[56], 
                    'PG' : i[57], 
                    'WC' : i[58], 
                    'SC' : i[59], 
                    'GA' : i[60], 
                    'UT' : i[61], 
                    'PM' : i[62], 
                    'OA' : i[63], 
                    'HC' : i[64], 
                    'HP' : i[65], 
                    'DA' : i[66] 



                        })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [7]:
###################################
## Using Pandas, check that data hs made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_documents", engine)
print(docs_table_df)

      id PT                                                 AU    BA    BE  \
0      1  J  Swift, SL; Glymour, MM; Elfassy, T; Lewis, C; ...  None  None
1      2  J  Pugliese, DN; Booth, JN; Deng, LQ; Anstey, DE;...  None  None
2      3  J  Hirahatake, KM; Jacobs, DR; Shikany, JM; Jiang...  None  None
3      4  J  Xiong, ZY; Li, JY; Zhong, XB; Zhang, SZ; Sun, ...  None  None
4      5  J  Sternfeld, B; Gabriel, KP; Jiang, SF; Whitaker...  None  None
..   ... ..                                                ...   ...   ...
742  743  J  DONAHUE, RP; JACOBS, DR; SIDNEY, S; WAGENKNECH...  None  None
743  744  J  LIU, K; BALLEW, C; JACOBS, DR; SIDNEY, S; SAVA...  None  None
744  745  J  JACOBS, DR; BURKE, GL; LIU, K; CUTTER, G; HUGH...  None  None
745  746  J  FRIEDMAN, GD; CUTTER, GR; DONAHUE, RP; HUGHES,...  None  None
746  747  J  HUGHES, GH; CUTTER, G; DONAHUE, R; FRIEDMAN, G...  None  None

       GP                                                 AF    BF    CA  \
0    None  Swift, Samuel L.; Glymour, M. Maria; Elfassy, ...  None  None
1    None  Pugliese, Daniel N.; Booth, John N., III; Deng...  None  None
2    None  Hirahatake, Kristin M.; Jacobs, David R., Jr.;...  None  None
3    None  Xiong, Zhenyu; Li, Jiaying; Zhong, Xiangbin; Z...  None  None
4    None  Sternfeld, Barbara; Gabriel, Kelley Pettee; Ji...  None  None
..    ...                                                ...   ...   ...
742  None  DONAHUE, RP; JACOBS, DR; SIDNEY, S; WAGENKNECH...  None  None
743  None  LIU, K; BALLEW, C; JACOBS, DR; SIDNEY, S; SAVA...  None  None
744  None  JACOBS, DR; BURKE, GL; LIU, K; CUTTER, G; HUGH...  None  None
745  None  FRIEDMAN, GD; CUTTER, GR; DONAHUE, RP; HUGHES,...  None  None
746  None  HUGHES, GH; CUTTER, G; DONAHUE, R; FRIEDMAN, G...  None  None

                                                    TI  ...  PG  \
0    Racial discrimination in medical care settings...  ...  12
1    Sex differences in masked hypertension: the Co...  ...   9
2    Cumulative average dietary pattern scores in y...  ...  12
3    Visit-to-Visit Fasting Glucose Variability in ...  ...   4
4    Risk Estimates for Diabetes and Hypertension w...  ...   8
..                                                 ...  ...  ..
742  DISTRIBUTION OF LIPOPROTEINS AND APOLIPOPROTEI...  ...   9
743  ETHNIC-DIFFERENCES IN BLOOD-PRESSURE, PULSE-RA...  ...   9
744  RELATIONSHIPS OF LOW-DENSITY LIPOPROTEIN CHOLE...  ...   7
745  CARDIA - STUDY DESIGN, RECRUITMENT, AND SOME C...  ...  12
746  RECRUITMENT IN THE CORONARY-ARTERY DISEASE RIS...  ...   6

                                                    WC  \
0                           Multidisciplinary Sciences
1                          Peripheral Vascular Disease
2                           Endocrinology & Metabolism
3                           Endocrinology & Metabolism
4                                       Sport Sciences
..                                                 ...
742  Cardiac & Cardiovascular Systems; Peripheral V...
743                        Peripheral Vascular Disease
744  Medicine, General & Internal; Medicine, Resear...
745  Health Care Sciences & Services; Public, Envir...
746  Medicine, Research & Experimental; Pharmacolog...

                                                    SC     GA  \
0                  Science & Technology - Other Topics  LP3ZM
1                   Cardiovascular System & Cardiology  KG1CQ
2                           Endocrinology & Metabolism  JT4ZE
3                           Endocrinology & Metabolism  JQ0GR
4                                       Sport Sciences  JO3XW
..                                                 ...    ...
742                 Cardiovascular System & Cardiology  AQ761
743                 Cardiovascular System & Cardiology  AK480
744  General & Internal Medicine; Research & Experi...  P1817
745  Health Care Sciences & Services; Public, Envir...  R5203
746  Research & Experimental Medicine; Pharmacology...  M0016

                      UT          PM                          OA    HC    HP  \
0    WOS:000534257500017  31860661.0  DOAJ Gold, Green Published  None  None
1    WOS:000509679200009  31246891.0                        None  None  None
2    WOS:000500998600007  31478081.0                        None  None  None
3    WOS:000498634000031  31548243.0                        None  None  None
4    WOS:000497515100010  31274682.0                        None  None  None
..                   ...         ...                         ...   ...   ...
742  WOS:A1989AQ76100010   2783079.0                      Bronze  None  None
743  WOS:A1989AK48000015   2759681.0                        None  None  None
744  WOS:A1988P181700006   3261566.0                        None  None  None
745  WOS:A1988R520300009   3204420.0                        None  None  None
746  WOS:A1987M001600007   3440391.0                        None  None  None

            DA
0    8/15/2020
1    8/15/2020
2    8/15/2020
3    8/15/2020
4    8/15/2020
..         ...
742  8/15/2020
743  8/15/2020
744  8/15/2020
745  8/15/2020
746  8/15/2020

[747 rows x 68 columns]

In [8]:
def load_2():
    wos_documents_org_enhanced_data = pd.read_csv("../static/data/wos_documents_org_enhanced.csv")
    wos_documents_org_enhanced_data_list = wos_documents_org_enhanced_data.values.tolist()
    #print(wos_documents_org_enhanced_data_list)
    return wos_documents_org_enhanced_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_2 = load_2()
    #print(data_2)
    for i in data_2:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Documents_Org_Enhanced(**{
                    'Organizations_Enhanced' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [9]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_documents_org_enhanced", engine)
print(docs_table_df)

      id               Organizations_Enhanced  records  percent
0      1       UNIVERSITY OF MINNESOTA SYSTEM      398   53.280
1      2  UNIVERSITY OF MINNESOTA TWIN CITIES      398   53.280
2      3         UNIVERSITY OF ALABAMA SYSTEM      377   50.469
3      4     UNIVERSITY OF ALABAMA BIRMINGHAM      372   49.799
4      5              NORTHWESTERN UNIVERSITY      351   46.988
..   ...                                  ...      ...      ...
442  443       WESTERN WYOMING COMMUNITY COLL        1    0.134
443  444                      YALE UNIVERSITY        1    0.134
444  445                  YEUNGNAM UNIVERSITY        1    0.134
445  446                    YONSEI UNIVERSITY        1    0.134
446  447      YONSEI UNIVERSITY HEALTH SYSTEM        1    0.134

[447 rows x 4 columns]

In [10]:
def load_3():
    wos_documents_funding_agencies_data = pd.read_csv("../static/data/wos_documents_funding_agencies.csv")
    wos_documents_funding_agencies_data_list = wos_documents_funding_agencies_data.values.tolist()
    #print(wos_documents_funding_agencies_data_list)
    return wos_documents_funding_agencies_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_3 = load_3()
    #print(data_3)
    for i in data_3:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Documents_Funding_Agencies(**{
                    'Funding_Agencies' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [11]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_documents_funding_agencies", engine)
print(docs_table_df)

      id                                   Funding_Agencies  records  percent
0      1  UNITED STATES DEPARTMENT OF HEALTH HUMAN SERVICES      662   88.621
1      2              NATIONAL INSTITUTES OF HEALTH NIH USA      661   88.487
2      3      NIH NATIONAL HEART LUNG BLOOD INSTITUTE NHLBI      617   82.597
3      4                NIH NATIONAL INSTITUTE ON AGING NIA      221   29.585
4      5                     UNIVERSITY OF MINNESOTA SYSTEM      155   20.750
..   ...                                                ...      ...      ...
357  358                WAKE FOREST UNIVERSITY YEAR 20 EXAM        1    0.134
358  359                                    WEIGHT WATCHERS        1    0.134
359  360                      WEIGHT WATCHERS INTERNATIONAL        1    0.134
360  361                          WORLD HEALTH ORGANIZATION        1    0.134
361  362                                          YALTA NIH        1    0.134

[362 rows x 4 columns]

In [12]:
def load_4():
    wos_documents_countries_data = pd.read_csv("../static/data/wos_documents_countries.csv")
    wos_documents_countries_data_list = wos_documents_countries_data.values.tolist()
    #print(wos_documents_countries_data_list)
    return wos_documents_countries_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_4 = load_4()
    #print(data_4)
    for i in data_4:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Documents_Countries(**{
                    'Countries_Regions' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [13]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_documents_countries", engine)
print(docs_table_df)

    id Countries_Regions  records  percent
0    1               USA      738   98.795
1    2            NORWAY      103   13.788
2    3       SOUTH KOREA       20    2.677
3    4   PEOPLES R CHINA       14    1.874
4    5       SWITZERLAND       14    1.874
5    6             JAPAN       13    1.740
6    7            BRAZIL       11    1.473
7    8            CANADA        9    1.205
8    9           ENGLAND        8    1.071
9   10            ISRAEL        8    1.071
10  11       NETHERLANDS        8    1.071
11  12           GERMANY        6    0.803
12  13           BELGIUM        5    0.669
13  14             SPAIN        5    0.669
14  15            FRANCE        2    0.268
15  16           IRELAND        2    0.268
16  17           NIGERIA        2    0.268
17  18    CZECH REPUBLIC        1    0.134
18  19           DENMARK        1    0.134
19  20           FINLAND        1    0.134
20  21            GREECE        1    0.134
21  22             ITALY        1    0.134
22  23     NORTH IRELAND        1    0.134
23  24          PORTUGAL        1    0.134
24  25          SCOTLAND        1    0.134
25  26            SWEDEN        1    0.134

In [14]:
def load_5():
    wos_documents_grant_numbers_data = pd.read_csv("../static/data/wos_documents_grant_numbers.csv")
    wos_documents_grant_numbers_data_list = wos_documents_grant_numbers_data.values.tolist()
    #print(wos_documents_grant_numbers_data_list)
    return wos_documents_grant_numbers_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_5 = load_5()
    #print(data_5)
    for i in data_5:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Documents_Grant_Numbers(**{
                    'Grant_Numbers' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [15]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_documents_grant_numbers", engine)
print(docs_table_df)

      id                 Grant_Numbers  records  percent
0      1                  N01-HC-48047    303.0   40.562
1      2                  N01-HC-48048    295.0   39.491
2      3                  N01-HC-48049    282.0   37.751
3      4                  N01-HC-95095    243.0   32.530
4      5                  N01-HC-48050    239.0   31.995
..   ...                           ...      ...      ...
795  796                 Y2-PC-0010-DC      1.0    0.134
796  797       YALTA: NIH 1RO1-HL53560      1.0    0.134
797  798  YALTA: NIH 1RO1-HL53560-01A1      1.0    0.134
798  799                  Z99 AG999999      1.0    0.134
799  800                  Z99 HL999999      1.0    0.134

[800 rows x 4 columns]

In [16]:
def load_6():
    wos_documents_citation_review_data = pd.read_csv("../static/data/wos_documents_citation_review.csv")
    wos_documents_citation_review_data_list = wos_documents_citation_review_data.values.tolist()
    #print(wos_documents_citation_review_data_list)
    return wos_documents_citation_review_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_6 = load_6()
    #print(data_6)
    for i in data_6:
        print([i[142]])
        #below is the Class name and column names from the database
        record = WoS_Documents_Citation_Review(**{
                        'Title' : i[0],
                        'Authors' : i[1],
                        'Corporate_Authors' : i[2],
                        'Editors' : i[3],
                        'Book_Editors' : i[4],
                        'Source_Title' : i[5],
                        'Publication_Date' : i[6],
                        'Publication_Year' : i[7],
                        'Volume' : i[8],
                        'Issue' : i[9],
                        'Part_Number' : i[10],
                        'Supplement' : i[11],
                        'Special_Issue' : i[12],
                        'Beginning_Page' : i[13],
                        'Ending_page' : i[14],
                        'Article_Number' : i[15],
                        'DOI' : i[16],
                        'Conference_Title' : i[17],
                        'Conference_Date' : i[18],
                        'Total_Citations' : i[19],
                        'Average_per_Year' : i[20],
                        'y1900' : i[21],
                        'y1901' : i[22],
                        'y1902' : i[23],
                        'y1903' : i[24],
                        'y1904' : i[25],
                        'y1905' : i[26],
                        'y1906' : i[27],
                        'y1907' : i[28],
                        'y1908' : i[29],
                        'y1909' : i[30],
                        'y1910' : i[31],
                        'y1911' : i[32],
                        'y1912' : i[33],
                        'y1913' : i[34],
                        'y1914' : i[35],
                        'y1915' : i[36],
                        'y1916' : i[37],
                        'y1917' : i[38],
                        'y1918' : i[39],
                        'y1919' : i[40],
                        'y1920' : i[41],
                        'y1921' : i[42],
                        'y1922' : i[43],
                        'y1923' : i[44],
                        'y1924' : i[45],
                        'y1925' : i[46],
                        'y1926' : i[47],
                        'y1927' : i[48],
                        'y1928' : i[49],
                        'y1929' : i[50],
                        'y1930' : i[51],
                        'y1931' : i[52],
                        'y1932' : i[53],
                        'y1933' : i[54],
                        'y1934' : i[55],
                        'y1935' : i[56],
                        'y1936' : i[57],
                        'y1937' : i[58],
                        'y1938' : i[59],
                        'y1939' : i[60],
                        'y1940' : i[61],
                        'y1941' : i[62],
                        'y1942' : i[63],
                        'y1943' : i[64],
                        'y1944' : i[65],
                        'y1945' : i[66],
                        'y1946' : i[67],
                        'y1947' : i[68],
                        'y1948' : i[69],
                        'y1949' : i[70],
                        'y1950' : i[71],
                        'y1951' : i[72],
                        'y1952' : i[73],
                        'y1953' : i[74],
                        'y1954' : i[75],
                        'y1955' : i[76],
                        'y1956' : i[77],
                        'y1957' : i[78],
                        'y1958' : i[79],
                        'y1959' : i[80],
                        'y1960' : i[81],
                        'y1961' : i[82],
                        'y1962' : i[83],
                        'y1963' : i[84],
                        'y1964' : i[85],
                        'y1965' : i[86],
                        'y1966' : i[87],
                        'y1967' : i[88],
                        'y1968' : i[89],
                        'y1969' : i[90],
                        'y1970' : i[91],
                        'y1971' : i[92],
                        'y1972' : i[93],
                        'y1973' : i[94],
                        'y1974' : i[95],
                        'y1975' : i[96],
                        'y1976' : i[97],
                        'y1977' : i[98],
                        'y1978' : i[99],
                        'y1979' : i[100],
                        'y1980' : i[101],
                        'y1981' : i[102],
                        'y1982' : i[103],
                        'y1983' : i[104],
                        'y1984' : i[105],
                        'y1985' : i[106],
                        'y1986' : i[107],
                        'y1987' : i[108],
                        'y1988' : i[109],
                        'y1989' : i[110],
                        'y1990' : i[111],
                        'y1991' : i[112],
                        'y1992' : i[113],
                        'y1993' : i[114],
                        'y1994' : i[115],
                        'y1995' : i[116],
                        'y1996' : i[117],
                        'y1997' : i[118],
                        'y1998' : i[119],
                        'y1999' : i[120],
                        'y2000' : i[121],
                        'y2001' : i[122],
                        'y2002' : i[123],
                        'y2003' : i[124],
                        'y2004' : i[125],
                        'y2005' : i[126],
                        'y2006' : i[127],
                        'y2007' : i[128],
                        'y2008' : i[129],
                        'y2009' : i[130],
                        'y2010' : i[131],
                        'y2011' : i[132],
                        'y2012' : i[133],
                        'y2013' : i[134],
                        'y2014' : i[135],
                        'y2015' : i[136],
                        'y2016' : i[137],
                        'y2017' : i[138],
                        'y2018' : i[139],
                        'y2019' : i[140],
                        'y2020' : i[141],
                        'y2021' : i[142],

                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]

In [17]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_documents_citation_review", engine)
print(docs_table_df)

      id                                              Title  \
0      1  PREVALENCE OF HYPERTROPHIC CARDIOMYOPATHY IN A...
1      2  CARDIA - STUDY DESIGN, RECRUITMENT, AND SOME C...
2      3  Racial discrimination and blood pressure: The ...
3      4  Dairy consumption, obesity, and the insulin re...
4      5  Fast-food habits, weight gain, and insulin res...
..   ...                                                ...
742  743    Physical Activity and Weight Gain Over 20 Years
743  744  RE: ALCOHOL CONSUMPTION IN YOUNG ADULTS AND IN...
744  745  Re: Objectively measured sleep characteristics...
745  746  INCONSISTENT ASSOCIATIONS OF CAFFEINE-CONTAINI...
746  747  RELATION BETWEEN SMOKING AND RESTING CARDIAC F...

                                               Authors Corporate_Authors  \
0    MARON, BJ; GARDIN, JM; FLACK, JM; GIDDING, SS;...              None
1    FRIEDMAN, GD; CUTTER, GR; DONAHUE, RP; HUGHES,...              None
2                                Krieger, N; Sidney, S              None
3    Pereira, MA; Jacobs, DR; Van Horn, L; Slattery...              None
4    Pereira, MA; Kartashov, AI; Ebbeling, CB; Van ...              None
..                                                 ...               ...
742          Jolley, Sarah; Porter, Brian; Amory, John              None
743  Halanych, Jewell H.; Safford, Monika M.; Kerte...              None
744  Lauderdale, Diane S.; Knutson, Kristen L.; Rat...              None
745  LEWIS, CE; FUNKHOUSER, E; HILNER, JE; BRAGG, C...              None
746  GIDDING, SS; XIE, XY; MANOLIO, T; FLACK, J; PE...              None

    Editors                       Book_Editors  \
0      None                               None
1      None                               None
2      None                               None
3      None                               None
4      None                               None
..      ...                                ...
742    None                               None
743    None                               None
744    None                               None
745    None                               None
746    None  Filer, LJ; Lauer, RM; Luepker, RV

                                          Source_Title Publication_Date  \
0                                          CIRCULATION      AUG 15 1995
1                     JOURNAL OF CLINICAL EPIDEMIOLOGY             1988
2                    AMERICAN JOURNAL OF PUBLIC HEALTH         OCT 1996
3     JAMA-JOURNAL OF THE AMERICAN MEDICAL ASSOCIATION      APR 24 2002
4                                               LANCET       JAN 1 2005
..                                                 ...              ...
742   JAMA-JOURNAL OF THE AMERICAN MEDICAL ASSOCIATION       APR 6 2011
743                   AMERICAN JOURNAL OF EPIDEMIOLOGY      SEP 15 2010
744                   AMERICAN JOURNAL OF EPIDEMIOLOGY      JAN 15 2007
745                   AMERICAN JOURNAL OF EPIDEMIOLOGY       OCT 1 1994
746  PREVENTION OF ATHEROSCLEROSIS AND HYPERTENSION...             1994

    Publication_Year Volume  ... y2012 y2013 y2014 y2015 y2016 y2017 y2018  \
0               1995   92.0  ...    67    68    71    94    81    76    72
1               1988   41.0  ...    51    51    60    60    54    68    69
2               1996   86.0  ...    43    37    30    34    46    31    29
3               2002  287.0  ...    50    56    41    38    30    31    22
4               2005  365.0  ...    61    60    59    58    52    51    55
..               ...    ...  ...   ...   ...   ...   ...   ...   ...   ...
742             2011  305.0  ...     0     0     0     0     0     0     0
743             2010  172.0  ...     0     0     0     0     0     0     0
744             2007  165.0  ...     0     0     0     0     0     0     0
745             1994  140.0  ...     0     0     0     0     0     0     0
746             1994   None  ...     0     0     0     0     0     0     0

    y2019 y2020 y2021
0      69    44     0
1      83    50     0
2      33    22     0
3      20     7     0
4      38    27     0
..    ...   ...   ...
742     0     0     0
743     0     0     0
744     0     0     0
745     0     0     0
746     0     0     0

[747 rows x 144 columns]

In [18]:
def load_7():
    wos_citations_wos_category_data = pd.read_csv("../static/data/wos_citations_wos_category.csv")
    wos_citations_wos_category_data_list = wos_citations_wos_category_data.values.tolist()
    #print(wos_citations_wos_category_data_list)
    return wos_citations_wos_category_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_7 = load_7()
    #print(data_7)
    for i in data_7:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Citations_WOS_Category(**{
                    'WOS_Category' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [19]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_citations_wos_category", engine)
print(docs_table_df)

      id                                       WOS_Category  records  percent
0      1           PUBLIC ENVIRONMENTAL OCCUPATIONAL HEALTH   4781.0   15.805
1      2                     CARDIAC CARDIOVASCULAR SYSTEMS   3554.0   11.749
2      3                                NUTRITION DIETETICS   3530.0   11.670
3      4                           ENDOCRINOLOGY METABOLISM   3108.0   10.275
4      5                          MEDICINE GENERAL INTERNAL   2388.0    7.894
..   ...                                                ...      ...      ...
191  192                       MEDIEVAL RENAISSANCE STUDIES      1.0    0.003
192  193                                           MYCOLOGY      1.0    0.003
193  194                            PSYCHOLOGY MATHEMATICAL      1.0    0.003
194  195                                       SOIL SCIENCE      1.0    0.003
195  196  (14 records (0.046%) do not contain data in th...      NaN      NaN

[196 rows x 4 columns]

In [20]:
def load_8():
    wos_citations_citaton_years_data = pd.read_csv("../static/data/wos_citations_citation_years.csv")
    wos_citations_citaton_years_data_list = wos_citations_citaton_years_data.values.tolist()
    #print(wos_citations_citaton_years_data_list)
    return wos_citations_citaton_years_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_8 = load_8()
    #print(data_8)
    for i in data_8:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Citations_Years(**{
                    'Publication_Year' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [21]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_citations_years", engine)
print(docs_table_df)

    id Publication_Year  records  percent
0    1           2020.0   1490.0    4.926
1    2           2019.0   2610.0    8.628
2    3           2018.0   2388.0    7.894
3    4           2017.0   2423.0    8.010
4    5           2016.0   2198.0    7.266
5    6           2015.0   2133.0    7.051
6    7           2014.0   1850.0    6.116
7    8           2013.0   1897.0    6.271
8    9           2012.0   1687.0    5.577
9   10           2011.0   1572.0    5.197
10  11           2010.0   1394.0    4.608
11  12           2009.0   1270.0    4.198
12  13           2008.0   1108.0    3.663
13  14           2007.0    958.0    3.167
14  15           2006.0    793.0    2.622
15  16           2005.0    678.0    2.241
16  17           2004.0    575.0    1.901
17  18           2003.0    511.0    1.689
18  19           2002.0    413.0    1.365
19  20           2001.0    355.0    1.174
20  21           2000.0    310.0    1.025
21  22           1999.0    299.0    0.988
22  23           1998.0    300.0    0.992
23  24           1997.0    280.0    0.926
24  25           1996.0    209.0    0.691
25  26           1995.0    183.0    0.605
26  27           1994.0    130.0    0.430
27  28           1993.0     88.0    0.291
28  29           1992.0     79.0    0.261
29  30           1991.0     51.0    0.169
30  31           1990.0     13.0    0.043
31  32           1989.0      4.0    0.013
32  33             None      NaN      NaN
33  34             None      NaN      NaN

In [22]:
def load_9():
    wos_citations_org_enhanced_data = pd.read_csv("../static/data/wos_citations_org_enhanced.csv")
    wos_citations_org_enhanced_data_list = wos_citations_org_enhanced_data.values.tolist()
    #print(wos_citations_org_enhanced_data_list)
    return wos_citations_org_enhanced_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_9 = load_9()
    #print(data_9)
    for i in data_9:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Citations_Org_Enhanced(**{
                    'Organization_Enhanced' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [23]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_citations_org_enhanced", engine)
print(docs_table_df)

          id                  Organization_Enhanced  records  percent
0          1        UNIVERSITY OF CALIFORNIA SYSTEM     2244    7.418
1          2                     HARVARD UNIVERSITY     1868    6.175
2          3         UNIVERSITY OF MINNESOTA SYSTEM     1190    3.934
3          4    UNIVERSITY OF MINNESOTA TWIN CITIES     1186    3.921
4          5  NATIONAL INSTITUTES OF HEALTH NIH USA     1179    3.898
...      ...                                    ...      ...      ...
13566  13567                         ZUCKER SCH MED        1    0.003
13567  13568           ZUHURATBABA MAH TATLINAR SOK        1    0.003
13568  13569                ZURCHER HOHENKLIN DAVOS        1    0.003
13569  13570  ZURICH UNIVERSITY OF APPLIED SCIENCES        1    0.003
13570  13571                          ZVEZDARA UNIV        1    0.003

[13571 rows x 4 columns]

In [24]:
def load_10():
    wos_citations_funding_agencies_data = pd.read_csv("../static/data/wos_citations_funding_agencies.csv")
    wos_citations_funding_agencies_data_list = wos_citations_funding_agencies_data.values.tolist()
    #print(wos_citations_funding_agencies_data_list)
    return wos_citations_funding_agencies_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_10 = load_10()
    #print(data_10)
    for i in data_10:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Citations_Funding_Agencies(**{
                    'Funding_Agencies' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [25]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_citations_funding_agencies", engine)
print(docs_table_df)

          id                                   Funding_Agencies  records  \
0          1  UNITED STATES DEPARTMENT OF HEALTH HUMAN SERVICES     8953
1          2              NATIONAL INSTITUTES OF HEALTH NIH USA     8803
2          3      NIH NATIONAL HEART LUNG BLOOD INSTITUTE NHLBI     3388
3          4                NIH NATIONAL INSTITUTE ON AGING NIA     1327
4          5  NIH NATIONAL INSTITUTE OF DIABETES DIGESTIVE K...      984
...      ...                                                ...      ...
16154  16155                                        ZONMW GRANT        1
16155  16156                                    ZONMW MEMORABEL        1
16156  16157                                ZONMW TAS PROGRAMME        1
16157  16158                                          ZS PHARMA        1
16158  16159      ZURICH CENTER OF INTEGRATIVE HUMAN PHYSIOLOGY        1

       percent
0       29.598
1       29.102
2       11.200
3        4.387
4        3.253
...        ...
16154    0.003
16155    0.003
16156    0.003
16157    0.003
16158    0.003

[16159 rows x 4 columns]

In [26]:
def load_11():
    wos_citations_source_title_data = pd.read_csv("../static/data/wos_citations_source_title.csv")
    wos_citations_source_title_data_list = wos_citations_source_title_data.values.tolist()
    #print(wos_citations_source_title_data_list)
    return wos_citations_source_title_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_11 = load_11()
    #print(data_11)
    for i in data_11:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Citations_Source_Title(**{
                    'Source_Title' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [27]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_citations_source_title", engine)
print(docs_table_df)

        id                                       Source_Title  records  \
0        1                                           PLOS ONE      592
1        2                   AMERICAN JOURNAL OF EPIDEMIOLOGY      327
2        3             AMERICAN JOURNAL OF CLINICAL NUTRITION      310
3        4                                        CIRCULATION      288
4        5                   INTERNATIONAL JOURNAL OF OBESITY      271
...    ...                                                ...      ...
4463  4464                   ZEITSCHRIFT FUR SPORTPSYCHOLOGIE        1
4464  4465  ZHURNAL NEVROPATOLOGII I PSIKHIATRII IMENI S S...        1
4465  4466  ZHURNAL VYSSHEI NERVNOI DEYATELNOSTI IMENI I P...        1
4466  4467                                            ZOOLOGY        1
4467  4468                   ZYWNOSC NAUKA TECHNOLOGIA JAKOSC        1

      percent
0       1.957
1       1.081
2       1.025
3       0.952
4       0.896
...       ...
4463    0.003
4464    0.003
4465    0.003
4466    0.003
4467    0.003

[4468 rows x 4 columns]

In [28]:
def load_12():
    wos_citations_book_series_title_data = pd.read_csv("../static/data/wos_citations_book_series_title.csv")
    wos_citations_book_series_title_data_list = wos_citations_book_series_title_data.values.tolist()
    #print(wos_citations_book_series_title_data_list)
    return wos_citations_book_series_title_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_12 = load_12()
    #print(data_12)
    for i in data_12:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Citations_Book_Series_Title(**{
                    'Book_Series_Title' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [29]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_citations_book_series_title", engine)
print(docs_table_df)

      id                                  Book_Series_Title  records  percent
0      1         ANNALS OF THE NEW YORK ACADEMY OF SCIENCES       34    0.112
1      2  WOODHEAD PUBLISHING SERIES IN FOOD SCIENCE TEC...       21    0.069
2      3      ADVANCES IN EXPERIMENTAL MEDICINE AND BIOLOGY       19    0.063
3      4                     ANNUAL REVIEW OF PUBLIC HEALTH       14    0.046
4      5                            CONTEMPORARY CARDIOLOGY       11    0.036
..   ...                                                ...      ...      ...
196  197                   TRANSPORTATION RESEARCH PROCEDIA        1    0.003
197  198      UNDERSTANDING POPULATION TRENDS AND PROCESSES        1    0.003
198  199  WILEY BLACKWELL HANDBOOKS OF BEHAVIORAL NEUROS...        1    0.003
199  200  WILEY HANDBOOKS IN CRIMINOLOGY AND CRIMINAL JU...        1    0.003
200  201                                  WORK LIFE BALANCE        1    0.003

[201 rows x 4 columns]

In [30]:
def load_13():
    wos_citations_meeting_title_data = pd.read_csv("../static/data/wos_citations_meeting_title.csv")
    wos_citations_meeting_title_data_list = wos_citations_meeting_title_data.values.tolist()
    #print(wos_citations_meeting_title_data_list)
    return wos_citations_meeting_title_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_13 = load_13()
    #print(data_13)
    for i in data_13:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Citations_Meeting_Title(**{
                    'Meeting_Title' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [31]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_citations_meeting_title", engine)
print(docs_table_df)

      id                                      Meeting_Title  records  percent
0      1  77TH SCIENTIFIC MEETING OF THE AMERICAN HEART ...        5    0.017
1      2  24TH ANNUAL NATIONAL SYMPOSIUM ON FAMILY ISSUE...        4    0.013
2      3  2ND WORLD SYMPOSIUM OF DAIRY PRODUCTS IN HUMAN...        4    0.013
3      4    BOGALUSA HEART STUDY 20TH ANNIVERSARY SYMPOSIUM        4    0.013
4      5  3RD SYMPOSIUM ON FROM PHENOTYPE TO GENE IN COM...        3    0.010
..   ...                                                ...      ...      ...
599  600                       WORLD CONGRESS OF NEPHROLOGY        1    0.003
600  601  WORLD DAIRY CONGRESS OF THE INTERNATIONAL DAIR...        1    0.003
601  602                          XII PAAVO NURMI SYMPOSIUM        1    0.003
602  603  XVITH SYMPOSIUM OF TH E SIGNE AND ANE GYLLENBE...        1    0.003
603  604  XVTH CONGRESS OF THE INTERNATIONAL SOCIETY ON ...        1    0.003

[604 rows x 4 columns]

In [32]:
def load_14():
    wos_citations_countries_data = pd.read_csv("../static/data/wos_citations_countries.csv")
    wos_citations_countries_data_list = wos_citations_countries_data.values.tolist()
    #print(wos_citations_countries_data_list)
    return wos_citations_countries_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_14 = load_14()
    #print(data_14)
    for i in data_14:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Citations_Countries(**{
                    'Countries_Regions' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [33]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_citations_countries", engine)
print(docs_table_df)

      id Countries_Regions  records  percent
0      1               USA    16562   54.752
1      2           ENGLAND     2220    7.339
2      3   PEOPLES R CHINA     1632    5.395
3      4            CANADA     1627    5.379
4      5         AUSTRALIA     1484    4.906
..   ...               ...      ...      ...
150  151           SOMALIA        1    0.003
151  152          SURINAME        1    0.003
152  153     TRINID TOBAGO        1    0.003
153  154        UZBEKISTAN        1    0.003
154  155             YEMEN        1    0.003

[155 rows x 4 columns]

In [34]:
def load_15():
    wos_citations_group_authors_data = pd.read_csv("../static/data/wos_citations_group_authors.csv")
    wos_citations_group_authors_data_list = wos_citations_group_authors_data.values.tolist()
    #print(wos_citations_group_authors_data_list)
    return wos_citations_group_authors_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_15 = load_15()
    #print(data_15)
    for i in data_15:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Citations_Group_Authors(**{
                    'Group_Authors' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [35]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_citations_group_authors", engine)
print(docs_table_df)

      id                      Group_Authors  records  percent
0      1     WORLD KIDNEY DAY STEERING COMM       47    0.155
1      2        COUNCIL CLINICAL CARDIOLOGY       16    0.053
2      3       COUNCIL CARDIOVASC DIS YOUNG       15    0.050
3      4                               IEEE       13    0.043
4      5  COUNCIL CARDIOVASC STROKE NURSING       11    0.036
..   ...                                ...      ...      ...
867  868                       YKKJ RES GRP        1    0.003
868  869             YOUNG HEARTS STUDY GRP        1    0.003
869  870       YOUNG MEN'S SURVEY STUDY GRP        1    0.003
870  871                ZPMCB VWD STUDY GRP        1    0.003
871  872                ZPMCB-VWD STUDY GRP        1    0.003

[872 rows x 4 columns]

In [36]:
def load_16():
    wos_citations_language_data = pd.read_csv("../static/data/wos_citations_languages.csv")
    wos_citations_language_data_list = wos_citations_language_data.values.tolist()
    #print(wos_citations_language_data_list)
    return wos_citations_language_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_16 = load_16()
    #print(data_16)
    for i in data_16:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Citations_Language(**{
                    'Language' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [37]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_citations_language", engine)
print(docs_table_df)

    id    Language  records  percent
0    1     ENGLISH    29676   98.106
1    2     SPANISH      190    0.628
2    3      GERMAN      111    0.367
3    4  PORTUGUESE       77    0.255
4    5      FRENCH       76    0.251
5    6     RUSSIAN       62    0.205
6    7      POLISH       14    0.046
7    8     ITALIAN       13    0.043
8    9     TURKISH        7    0.023
9   10   HUNGARIAN        5    0.017
10  11      KOREAN        5    0.017
11  12    JAPANESE        3    0.010
12  13     CHINESE        1    0.003
13  14       CZECH        1    0.003
14  15       DUTCH        1    0.003
15  16       GREEK        1    0.003
16  17   ICELANDIC        1    0.003
17  18  INDONESIAN        1    0.003
18  19     SERBIAN        1    0.003
19  20      SLOVAK        1    0.003
20  21   SLOVENIAN        1    0.003
21  22   UKRAINIAN        1    0.003

In [38]:
def load_17():
    wos_citations_grant_numbers_data = pd.read_csv("../static/data/wos_citations_grant_numbers.csv")
    wos_citations_grant_numbers_data_list = wos_citations_grant_numbers_data.values.tolist()
    #print(wos_citations_grant_numbers_data_list)
    return wos_citations_grant_numbers_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_17 = load_17()
    #print(data_17)
    for i in data_17:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Citations_Grant_Numbers(**{
                    'Grant_Numbers' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [39]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_citations_grant_numbers", engine)
print(docs_table_df)

          id     Grant_Numbers  records  percent
0          1      N01-HC-48047    333.0    1.101
1          2      N01-HC-48048    322.0    1.064
2          3      N01-HC-48049    310.0    1.025
3          4      N01-HC-95095    273.0    0.903
4          5      N01-HC-48050    268.0    0.886
...      ...               ...      ...      ...
28543  28544   veni 916.12.154      1.0    0.003
28544  28545       xywm2015129      1.0    0.003
28545  28546  z151100004015175      1.0    0.003
28546  28547             zd056      1.0    0.003
28547  28548             zd057      1.0    0.003

[28548 rows x 4 columns]

In [40]:
def load_18():
    incites_documents_data = pd.read_csv("../static/data/incites_documents.csv")
    incites_documents_data_list = incites_documents_data.values.tolist()
    #print(incites_documents_data_list)
    return incites_documents_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_18 = load_18()
    #print(data_18)
    for i in data_18:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = InCites_Documents(**{
                'Accession_Number' : i[0],
                'DOI' : i[1],
                'Pubmed_ID' : i[2],
                'Article_Title' : i[3],
                'Link' : i[4],
                'Authors' : i[5],
                'Source' : i[6],
                'Research_Area' : i[7],
                'Document_Type' : i[8],
                'Volume' : i[9],
                'Issue' : i[10],
                'Pages' : i[11],
                'Publication_Date' : i[12],
                'Times_Cited' : i[13],
                'Journal_Expected_Citations' : i[14],
                'Category_Expected_Citations' : i[15],
                'Journal_Normalized_Citation_Impact' : i[16],
                'Category_Normalized_Citation_Impact' : i[17],
                'Percentile_in_Subject_Area' : i[18],
                'Journal_Impact_Factor' : i[19]


                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [41]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM incites_documents", engine)
print(docs_table_df)

      id     Accession_Number                                 DOI  \
0      1  WOS:A1987M001600007                                None
1      2  WOS:A1988R520300009        10.1016/0895-4356(88)90080-7
2      3  WOS:A1988P181700006                                None
3      4  WOS:A1989AY60100007  10.1093/oxfordjournals.aje.a115424
4      5  WOS:A1989AQ76100010              10.1161/01.ATV.9.5.656
..   ...                  ...                                 ...
742  743  WOS:000458579400007                   10.1111/jch.13474
743  744  WOS:000468336900035         10.1016/j.ypmed.2019.03.039
744  745  WOS:000488197600026                 10.1093/ajcn/nqz154
745  746  WOS:000460693400012                   10.1002/eat.23020
746  747  WOS:000478894000026   10.1161/HYPERTENSIONAHA.119.13069

            Pubmed_ID                                      Article_Title  \
0     MEDLINE:3440391  RECRUITMENT IN THE CORONARY-ARTERY DISEASE RIS...
1     MEDLINE:3204420  CARDIA - STUDY DESIGN, RECRUITMENT, AND SOME C...
2     MEDLINE:3261566  RELATIONSHIPS OF LOW-DENSITY LIPOPROTEIN CHOLE...
3     MEDLINE:2683750  RELATION OF BODY FATNESS AND ITS DISTRIBUTION ...
4     MEDLINE:2783079  DISTRIBUTION OF LIPOPROTEINS AND APOLIPOPROTEI...
..                ...                                                ...
742  MEDLINE:30719843  Race and sex differences in asleep blood press...
743  MEDLINE:30940573  Perceived and objective characteristics of the...
744  MEDLINE:31374564  Cumulative intake of artificially sweetened an...
745  MEDLINE:30636022  Problematic eating behaviors and attitudes pre...
746  MEDLINE:31256722  Early Onset Hypertension Is Associated With Hy...

                                                  Link  \
0    https://gateway.webofknowledge.com/gateway/Gat...
1    https://gateway.webofknowledge.com/gateway/Gat...
2    https://gateway.webofknowledge.com/gateway/Gat...
3    https://gateway.webofknowledge.com/gateway/Gat...
4    https://gateway.webofknowledge.com/gateway/Gat...
..                                                 ...
742  https://gateway.webofknowledge.com/gateway/Gat...
743  https://gateway.webofknowledge.com/gateway/Gat...
744  https://gateway.webofknowledge.com/gateway/Gat...
745  https://gateway.webofknowledge.com/gateway/Gat...
746  https://gateway.webofknowledge.com/gateway/Gat...

                                               Authors  \
0    Hughes, GH; Cutter, G; Donahue, R; Friedman, G...
1    Friedman, GD; Cutter, GR; Donahue, RP; Hughes,...
2    Jacobs, DR; Burke, GL; Liu, K; Cutter, G; Hugh...
3    Folsom, AR; Burke, GL; Ballew, C; Jacobs, DR; ...
4    Donahue, RP; Jacobs, DR; Sidney, S; Wagenknech...
..                                                 ...
742  Booth, John N., III; Anstey, D. Edmund; Bello,...
743  Whitaker, Kara M.; Xiao, Qian; Gabriel, Kelley...
744  Hirahatake, Kristin M.; Jacobs, David R., Jr.;...
745  Yoon, Cynthia; Jacobs, David R.; Duprez, Danie...
746  Suvila, Karri; McCabe, Elizabeth L.; Lehtonen,...

                                        Source  \
0                   CONTROLLED CLINICAL TRIALS
1             JOURNAL OF CLINICAL EPIDEMIOLOGY
2                  ANNALS OF CLINICAL RESEARCH
3             AMERICAN JOURNAL OF EPIDEMIOLOGY
4                             ARTERIOSCLEROSIS
..                                         ...
742           JOURNAL OF CLINICAL HYPERTENSION
743                        PREVENTIVE MEDICINE
744     AMERICAN JOURNAL OF CLINICAL NUTRITION
745  INTERNATIONAL JOURNAL OF EATING DISORDERS
746                               HYPERTENSION

                                         Research_Area Document_Type  ...  \
0    PHARMACOLOGY & PHARMACY; MEDICINE, RESEARCH & ...       Article  ...
1    PUBLIC, ENVIRONMENTAL & OCCUPATIONAL HEALTH; H...       Article  ...
2                    MEDICINE, RESEARCH & EXPERIMENTAL       Article  ...
3          PUBLIC, ENVIRONMENTAL & OCCUPATIONAL HEALTH       Article  ...
4    CARDIAC & CARDIOVASCULAR SYSTEMS; PERIPHERAL V...       Article  ...
..                                                 ...           ...  ...
742                        PERIPHERAL VASCULAR DISEASE       Article  ...
743        PUBLIC, ENVIRONMENTAL & OCCUPATIONAL HEALTH       Article  ...
744                              NUTRITION & DIETETICS       Article  ...
745  NUTRITION & DIETETICS; PSYCHIATRY; PSYCHOLOGY;...       Article  ...
746                        PERIPHERAL VASCULAR DISEASE       Article  ...

     Issue      Pages Publication_Date Times_Cited  \
0        4    S68-S73             1987       160.0
1       11  1105-1116             1988       956.0
2    2-Jan      32-38             1988        18.0
3        5    911-924             1989       131.0
4        5    656-664             1989        86.0
..     ...        ...              ...         ...
742      2    184-192             2019         5.0
743   None    242-249             2019         0.0
744      3    733-741             2019         2.0
745      3    304-308             2019         0.0
746      2    305-312             2019         3.0

     Journal_Expected_Citations  Category_Expected_Citations  \
0                     39.538462                        24.70
1                     65.869231                        26.57
2                     17.262295                        29.83
3                     92.862222                        27.03
4                     81.165217                        34.76
..                          ...                          ...
742                    1.346154                         2.23
743                    1.587814                         1.23
744                    3.076305                         2.11
745                    1.951807                         1.65
746                    3.750929                         2.23

     Journal_Normalized_Citation_Impact  Category_Normalized_Citation_Impact  \
0                                  4.05                               6.4769
1                                 14.51                              35.9808
2                                  1.04                               0.6035
3                                  1.41                               4.8465
4                                  1.06                               2.4740
..                                  ...                                  ...
742                                3.71                               2.2425
743                                0.00                               0.0000
744                                0.65                               0.9478
745                                0.00                               0.0000
746                                0.80                               1.3455

     Percentile_in_Subject_Area  Journal_Impact_Factor
0                        1.1293                    NaN
1                        0.0913                  4.952
2                       34.6988                    NaN
3                        2.9214                  4.526
4                        8.0000                    NaN
..                          ...                    ...
742                     12.0022                  2.719
743                    100.0000                  3.788
744                     40.5809                  6.766
745                    100.0000                  3.668
746                     24.9779                  7.713

[747 rows x 21 columns]

In [42]:
def load_19():
    incites_documents_journals_data = pd.read_csv("../static/data/incites_documents_journals.csv")
    incites_documents_journals_data_list = incites_documents_journals_data.values.tolist()
    #print(incites_documents_journals_data_list)
    return incites_documents_journals_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_19 = load_19()
    #print(data_19)
    for i in data_19:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = InCites_Documents_Journals(**{
                    'Name' : i[0],
                    'Rank' : i[1],
                    'Web_of_Science_Documents' : i[2],
                    'Times_Cited' : i[3],
                    'Percent_Docs_Cited' : i[4],
                    'Quartile' : i[5],
                    'Five_Year_Impact_Factor' : i[6],
                    'Article_Influence' : i[7],
                    'Category_Normalized_Citation_Impact' : i[8],
                    'Cited_Half_Life' : i[9],
                    'Eigenfactor' : i[10],
                    'Immediacy_Index' : i[11],
                    'Impact_Factor_wo_Self_Cites' : i[12],
                    'Journal_Impact_Factor' : i[13],
                    'Journal_Normalized_Citation_Impact' : i[14],
                    'Percent_All_Open_Access_Documents' : i[15],
                    'Percent_Bronze_Documents' : i[16],
                    'Percent_DOAJ_Gold_Documents' : i[17],
                    'Percent_Green_Accepted_Documents' : i[18],
                    'Percent_Green_Published_Documents' : i[19],
                    'Percent_Other_Gold_Documents' : i[20],
                    'All_Open_Access_Documents' : i[21],
                    'Bronze_Documents' : i[22],
                    'DOAJ_Gold_Documents' : i[23],
                    'Green_Accepted_Documents' : i[24],
                    'Green_Published_Documents' : i[25],
                    'Other_Gold_Documents' : i[26]


                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [43]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM incites_documents_journals", engine)
print(docs_table_df)

      id                                               Name Rank  \
0      1   JAMA-JOURNAL OF THE AMERICAN MEDICAL ASSOCIATION    1
1      2                   AMERICAN JOURNAL OF EPIDEMIOLOGY    2
2      3                                        CIRCULATION    3
3      4                  AMERICAN JOURNAL OF PUBLIC HEALTH    4
4      5             AMERICAN JOURNAL OF CLINICAL NUTRITION    5
..   ...                                                ...  ...
213  214  PREGNANCY HYPERTENSION-AN INTERNATIONAL JOURNA...  213
214  215                               CLINICAL EPIGENETICS  213
215  216    JOURNAL OF THE AMERICAN PHARMACISTS ASSOCIATION  213
216  217                 AMERICAN JOURNAL OF NEURORADIOLOGY  213
217  218                        NICOTINE & TOBACCO RESEARCH  213

     Web_of_Science_Documents  Times_Cited  Percent_Docs_Cited Quartile  \
0                          18         3150           88.888889       Q1
1                          56         3021           92.857143       Q1
2                          17         2546          100.000000       Q1
3                          19         2232           94.736842       Q1
4                          22         1408           95.454545       Q1
..                        ...          ...                 ...      ...
213                         1            0            0.000000       Q2
214                         1            0            0.000000       Q1
215                         1            0            0.000000       Q2
216                         1            0            0.000000       Q1
217                         1            0            0.000000       Q1

     Five_Year_Impact_Factor  Article_Influence  \
0                     47.677             21.712
1                      5.212              2.311
2                     21.054              8.609
3                      6.006              2.576
4                      7.831              2.330
..                       ...                ...
213                    2.761              0.868
214                    5.695              1.487
215                    2.493              0.538
216                    3.853              1.176
217                    4.138              1.450

     Category_Normalized_Citation_Impact  ...  Percent_DOAJ_Gold_Documents  \
0                               5.057072  ...                          0.0
1                               1.902686  ...                          0.0
2                               4.368553  ...                          0.0
3                               3.802447  ...                          0.0
4                               2.096418  ...                          0.0
..                                   ...  ...                          ...
213                             0.000000  ...                          0.0
214                             0.000000  ...                        100.0
215                             0.000000  ...                          0.0
216                             0.000000  ...                          0.0
217                             0.000000  ...                          0.0

     Percent_Green_Accepted_Documents  Percent_Green_Published_Documents  \
0                           33.333333                          11.111111
1                            1.785714                          41.071429
2                           47.058824                          11.764706
3                           15.789474                         100.000000
4                            0.000000                          59.090909
..                                ...                                ...
213                        100.000000                           0.000000
214                          0.000000                         100.000000
215                          0.000000                           0.000000
216                          0.000000                           0.000000
217                          0.000000                         100.000000

     Percent_Other_Gold_Documents  All_Open_Access_Documents  \
0                        0.000000                       14.0
1                        3.571429                       43.0
2                        0.000000                       13.0
3                        0.000000                       19.0
4                        0.000000                       14.0
..                            ...                        ...
213                      0.000000                        1.0
214                      0.000000                        1.0
215                      0.000000                        0.0
216                    100.000000                        1.0
217                      0.000000                        1.0

     Bronze_Documents  DOAJ_Gold_Documents  Green_Accepted_Documents  \
0                  13                    0                         6
1                  39                    0                         1
2                   9                    0                         8
3                  10                    0                         3
4                  14                    0                         0
..                ...                  ...                       ...
213                 0                    0                         1
214                 0                    1                         0
215                 0                    0                         0
216                 0                    0                         0
217                 0                    0                         0

     Green_Published_Documents  Other_Gold_Documents
0                            2                     0
1                           23                     2
2                            2                     0
3                           19                     0
4                           13                     0
..                         ...                   ...
213                          0                     0
214                          1                     0
215                          0                     0
216                          0                     1
217                          1                     0

[218 rows x 28 columns]

In [44]:
def load_20():
    incites_citations_data = pd.read_csv("../static/data/incites_citations.csv")
    incites_citations_data_list = incites_citations_data.values.tolist()
    #print(incites_citations_data_list)
    return incites_citations_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_20 = load_20()
    #print(data_20)
    for i in data_20:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = InCites_Citations(**{
                    'Accession_Number' : i[0],
                    'DOI' : i[1],
                    'Pubmed_ID' : i[2],
                    'Article_Title' : i[3],
                    'Link' : i[4],
                    'Authors' : i[5],
                    'Source' : i[6],
                    'Research_Area' : i[7],
                    'Document_Type' : i[8],
                    'Volume' : i[9],
                    'Issue' : i[10],
                    'Pages' : i[11],
                    'Publication_Date' : i[12],
                    'Times_Cited' : i[13],
                    'Journal_Expected_Citations' : i[14],
                    'Category_Expected_Citations' : i[15],
                    'Journal_Normalized_Citation_Impact' : i[16],
                    'Category_Normalized_Citation_Impact' : i[17],
                    'Percentile_in_Subject_Area' : i[18],
                    'Journal_Impact_Factor' : i[19]


                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    #print('session closed')

In [45]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM incites_citations", engine)
print(docs_table_df)

          id     Accession_Number                                 DOI  \
0          1  WOS:000519746400002         10.1007/978-981-10-8405-8_2
1          2  WOS:000507918600001               10.1089/jop.2019.0048
2          3  WOS:000540241000003           10.1016/j.jbi.2020.103427
3          4  WOS:000531205200001            10.3389/fendo.2020.00204
4          5  WOS:000531867900014                  10.1037/dev0000919
...      ...                  ...                                 ...
29895  29896  WOS:A1990EJ67600002                  10.1007/BF00844831
29896  29897  WOS:A1989AY60100007  10.1093/oxfordjournals.aje.a115424
29897  29898  WOS:A1989AQ76100010              10.1161/01.ATV.9.5.656
29898  29899  WOS:A1989AK48000015             10.1161/01.HYP.14.2.218
29899  29900  WOS:A1989AJ35700004        10.1016/0091-7435(89)90004-2

              Pubmed_ID                                      Article_Title  \
0                  None  Tissue-Mimicking Materials for Cardiac Imaging...
1      MEDLINE:31951153  The Ocular Protective Effects of Nano/Submicro...
2      MEDLINE:32339748  Multi-modal interactive fusion method for dete...
3      MEDLINE:32351450  Spinal Cord Injury as a Model of Bone-Muscle I...
4      MEDLINE:32223295  Subjective Social Status and Health During Hig...
...                 ...                                                ...
29895   MEDLINE:2273523  SELECTION, TRAINING, AND QUALITY-CONTROL OF TY...
29896   MEDLINE:2683750  RELATION OF BODY FATNESS AND ITS DISTRIBUTION ...
29897   MEDLINE:2783079  DISTRIBUTION OF LIPOPROTEINS AND APOLIPOPROTEI...
29898   MEDLINE:2759681  ETHNIC-DIFFERENCES IN BLOOD-PRESSURE, PULSE-RA...
29899   MEDLINE:2798368  AN ASSESSMENT OF CALORIC-INTAKE AS AN INDICATO...

                                                    Link  \
0      https://gateway.webofknowledge.com/gateway/Gat...
1      https://gateway.webofknowledge.com/gateway/Gat...
2      https://gateway.webofknowledge.com/gateway/Gat...
3      https://gateway.webofknowledge.com/gateway/Gat...
4      https://gateway.webofknowledge.com/gateway/Gat...
...                                                  ...
29895  https://gateway.webofknowledge.com/gateway/Gat...
29896  https://gateway.webofknowledge.com/gateway/Gat...
29897  https://gateway.webofknowledge.com/gateway/Gat...
29898  https://gateway.webofknowledge.com/gateway/Gat...
29899  https://gateway.webofknowledge.com/gateway/Gat...

                                                 Authors  \
0      Yusof, Nurul Shafiqa Mohd; Dewi, Dyah Ekashant...
1      Yeh, Po-Ting; Chen, Yun-Ju; Lin, Nien-Chen; Ye...
2          Zhang, Huijun; Cao, Lei; Feng, Ling; Yang, MO
3      Invernizzi, Marco; de Sire, Alessandro; Reno, ...
4      Rahal, Danny; Huynh, Virginia; Cole, Steve; Se...
...                                                  ...
29895  Tallmer, J; Scherwitz, L; Chesney, M; Hecker, ...
29896  Folsom, AR; Burke, GL; Ballew, C; Jacobs, DR; ...
29897  Donahue, RP; Jacobs, DR; Sidney, S; Wagenknech...
29898  Liu, K; Ballew, C; Jacobs, DR; Sidney, S; Sava...
29899             Slattery, ML; Jacobs, DR; Nichaman, MZ

                                                  Source  \
0      CARDIOVASCULAR ENGINEERING: TECHNOLOGICAL ADVA...
1        JOURNAL OF OCULAR PHARMACOLOGY AND THERAPEUTICS
2                      JOURNAL OF BIOMEDICAL INFORMATICS
3                             FRONTIERS IN ENDOCRINOLOGY
4                               DEVELOPMENTAL PSYCHOLOGY
...                                                  ...
29895                     JOURNAL OF BEHAVIORAL MEDICINE
29896                   AMERICAN JOURNAL OF EPIDEMIOLOGY
29897                                   ARTERIOSCLEROSIS
29898                                       HYPERTENSION
29899                                PREVENTIVE MEDICINE

                                           Research_Area Document_Type  ...  \
0      CARDIAC & CARDIOVASCULAR SYSTEMS; ENGINEERING,...       Article  ...
1                 OPHTHALMOLOGY; PHARMACOLOGY & PHARMACY       Article  ...
2      COMPUTER SCIENCE, INTERDISCIPLINARY APPLICATIO...       Article  ...
3                             ENDOCRINOLOGY & METABOLISM        Review  ...
4                              PSYCHOLOGY, DEVELOPMENTAL       Article  ...
...                                                  ...           ...  ...
29895                               PSYCHOLOGY, CLINICAL       Article  ...
29896        PUBLIC, ENVIRONMENTAL & OCCUPATIONAL HEALTH       Article  ...
29897  CARDIAC & CARDIOVASCULAR SYSTEMS; PERIPHERAL V...       Article  ...
29898                        PERIPHERAL VASCULAR DISEASE       Article  ...
29899        PUBLIC, ENVIRONMENTAL & OCCUPATIONAL HEALTH       Article  ...

      Issue      Pages Publication_Date Times_Cited  \
0      None      35-63             2020         0.0
1         3    179-189             2020         0.0
2      None       None             2020         0.0
3      None       None             2020         1.0
4         6  1220-1232             2020         0.0
...     ...        ...              ...         ...
29895     5    449-466             1990         3.0
29896     5    911-924             1989       131.0
29897     5    656-664             1989        86.0
29898     2    218-226             1989        75.0
29899     4    444-451             1989        19.0

       Journal_Expected_Citations  Category_Expected_Citations  \
0                        0.000000                         0.38
1                        0.000000                         0.22
2                        0.163934                         0.35
3                        0.256000                         0.45
4                        0.543478                         0.47
...                           ...                          ...
29895                   35.400000                        36.65
29896                   92.862222                        27.03
29897                   81.165217                        34.76
29898                   68.058537                        40.99
29899                   29.900000                        27.03

       Journal_Normalized_Citation_Impact  \
0                                    0.00
1                                    0.00
2                                    0.00
3                                    3.91
4                                    0.00
...                                   ...
29895                                0.08
29896                                1.41
29897                                1.06
29898                                1.10
29899                                0.64

       Category_Normalized_Citation_Impact  Percentile_in_Subject_Area  \
0                                   0.0000                    100.0000
1                                   0.0000                    100.0000
2                                   0.0000                    100.0000
3                                   2.2221                     26.4512
4                                   0.0000                    100.0000
...                                    ...                         ...
29895                               0.0818                     81.7608
29896                               4.8465                      2.9214
29897                               2.4740                      8.0000
29898                               1.8297                     14.4499
29899                               0.7029                     34.7295

       Journal_Impact_Factor
0                        NaN
1                      1.925
2                      3.526
3                      3.644
4                      3.063
...                      ...
29895                  2.988
29896                  4.526
29897                    NaN
29898                  7.713
29899                  3.788

[29900 rows x 21 columns]

In [46]:
def load_21():
    wos_citations_research_areas_data = pd.read_csv("../static/data/wos_citations_research_areas.csv")
    wos_citations_research_areas_data_list = wos_citations_research_areas_data.values.tolist()
    #print(wos_citations_research_areas_data_list)
    return wos_citations_research_areas_data_list

#Create the session
session = sessionmaker()
session.configure(bind=engine)
s = session()

try:
    data_21 = load_21()
    #print(data_21)
    for i in data_21:
        #print([i[0]])
        #below is the Class name and column names from the database
        record = WoS_Citations_Research_Areas(**{
                    'Research_Areas' : i[0], 
                    'records' : i[1], 
                    'percent' : i[2] 
                 })
        #print(record)
        s.add(record) #Add all the records

    s.commit() #Attempt to commit all the records   

#http://docs.pyexcel.org/en/latest/showcases/db_injection.html
except:
    s.rollback() #Rollback the changes on error
finally:
    s.close() #Close the connection
    print('session closed')

session closed

In [47]:
###################################
## Using Pandas, check that data has made it into database
###################################

docs_table_df = pd.read_sql_query("SELECT * FROM wos_citations_research_areas", engine)
print(docs_table_df)

OperationalError: (sqlite3.OperationalError) no such table: wos_citations_research_areas
[SQL: SELECT * FROM wos_citations_research_areas]
(Background on this error at: http://sqlalche.me/e/13/e3q8)